export const ADD_TODO = 'ADD_TODO'
export const ADD_TODOS = 'ADD_TODOS'
export const DELETE_TODO = 'DELETE_TODO'
export const CHANGE_STATUS_TODO = 'CHANGE_STATUS_TODO'
export const CLEAR_TODOS = 'CLEAR_TODOS' 